esphome:
  name: radsens
  friendly_name: RadSens
  libraries:
    - Wire

external_components:
  - source: github://D1m0k/esphome-radsens@1.0.4
    components: [radsens]
    refresh: 10s

i2c:
  - id: bus_a
    frequency: 400kHz

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "RadSens Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

radsens:
  sensitivity: 825

sensor:
  - platform: radsens
    dynamic_intensity:
      name: "Dynamic Intensity"
    static_intensity:
      name: "Static Intensity"
    counts_per_minute:
      name: "Counts Per Minute"
    counts_per_polling:
      name: "Counts Per Polling"
    radsens_max_cpp:
      name: "RadSens Max CPP"
    max_cpp_timestamp:
      name: "Max CPP Timestamp (s uptime)"
    radsens_max_cpm:
      name: "RadSens Max CPM"
    max_cpm_timestamp:
      name: "Max CPM Timestamp (s uptime)"
    total_cpp:
      name: "Total CPP"
    uptime:
      name: "Uptime"
    accumulated_dose_ur:
      name: "Accumulated Dose (uR)"
    accumulated_dose_msv:
      name: "Accumulated Dose (mSv)"

switch:
  - platform: radsens
    control_led:
      name: "Impulse LED"
      restore_mode: RESTORE_DEFAULT_ON
    control_high_voltage:
      name: "High Voltage Enable"
      restore_mode: RESTORE_DEFAULT_ON
    control_low_power:
      name: "Low Power Mode"
      restore_mode: RESTORE_DEFAULT_OFF

number:
  - platform: radsens
    polling_interval:
      name: "Polling Interval"
